version: '3.9'
services:
  plantuml-editor:
    #image: heinrichad/plantuml-editor:master
    image: heinrichad/plantuml-editor:develop
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    restart: always
    container_name: plantuml-editor
    environment:
      - VUE_APP_URL=http://localhost:8080
      - VUE_APP_CDN=http://localhost:4000
      #- TZ=...
    ports:
      - 8080:80
  plantuml-server:
    image: plantuml/plantuml-server
    container_name: "plantuml-server"
    environment:
      - PLANTUML_LIMIT_SIZE=16384
      - PLANTUML_STATS=on
      - ALLOW_PLANTUML_INCLUDE=true
    ports:
      - 4000:8080
